<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" total="1" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="1151" started-at="2018-10-29T12:54:40Z" finished-at="2018-10-29T12:54:41Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="1151" started-at="2018-10-29T12:54:40Z" finished-at="2018-10-29T12:54:41Z">
      <class name="sanity.ForgotPasswordTestCase">
        <test-method status="PASS" signature="initBrowser()[pri:0, instance:sanity.ForgotPasswordTestCase@2ef3eef9]" name="initBrowser" is-config="true" duration-ms="7697" started-at="2018-10-29T18:24:32Z" finished-at="2018-10-29T18:24:40Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- initBrowser -->
        <test-method status="PASS" signature="testdata()[pri:0, instance:sanity.ForgotPasswordTestCase@2ef3eef9]" name="testdata" is-config="true" duration-ms="0" started-at="2018-10-29T18:24:40Z" finished-at="2018-10-29T18:24:40Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testdata -->
        <test-method status="FAIL" signature="validforgotpassword_test()[pri:0, instance:sanity.ForgotPasswordTestCase@2ef3eef9]" name="validforgotpassword_test" duration-ms="1147" started-at="2018-10-29T18:24:40Z" finished-at="2018-10-29T18:24:41Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[User Failed to Login with valid credentials expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: User Failed to Login with valid credentials expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:494)
	at org.testng.Assert.assertTrue(Assert.java:42)
	at sanity.ForgotPasswordTestCase.validforgotpassword_test(ForgotPasswordTestCase.java:95)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1198)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1123)
	at org.testng.TestNG.run(TestNG.java:1031)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- validforgotpassword_test -->
        <test-method status="PASS" signature="destroy()[pri:0, instance:sanity.ForgotPasswordTestCase@2ef3eef9]" name="destroy" is-config="true" duration-ms="192" started-at="2018-10-29T18:24:41Z" finished-at="2018-10-29T18:24:42Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- destroy -->
      </class> <!-- sanity.ForgotPasswordTestCase -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
